spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:h2:file:///~/bloom?options=DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password: pass
  sql:
    init:
      encoding: UTF-8
