spring:
  main:
    banner-mode: off
  datasource:
    name: bloom
    url: jdbc:h2:file:~/bloom;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password: pass
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        enable_lazy_load_no_trans: true

plugins:
  root: ../bloom-plugins/build/plugins

#logging.level:
#  com: debug
#  org: debug
